Repository tysonkaufmann/su-go, pull requests merged in 2021-04, with the labels that each got.

#124 Refactor MapContainer. Add marker clicking functionality.
  README.md
  frontend/src/actions/routes.js
  frontend/src/components/mapContainer.component.js
  frontend/src/components/markerComponent.component.js
  frontend/src/components/overviewMap.component.js
  frontend/src/components/routePage.component.js
  frontend/src/reducers/routesReducer.js
Labels: Pull Request

#128 Add countdown timer to map card. Add voting system to the frontend.
  backend/controllers/routes.js
  backend/controllers/vote.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/actions/routes.js
  frontend/src/components/navbar.component.js
  frontend/src/components/routePage.component.js
  frontend/src/reducers/routesReducer.js
Labels: Pull Request

#129 Add documentation artifacts for voting feature
  documentation/images/class diagram.png
  documentation/images/sequence - viewroutevotescore.png
  documentation/images/sequence - voteroute.png
Labels: Pull Request, documentation

#133 Add ESLint linting workflow
  .github/workflows/lint.yml
  .github/workflows/node.js.yml
  README.md
  backend/.eslintrc.json
  backend/__tests__/integration/routes.js
  backend/__tests__/integration/user.js
  backend/__tests__/integration/vote.js
  backend/__tests__/unit/controllers/routes.js
  backend/__tests__/unit/controllers/user.js
  backend/__tests__/unit/controllers/vote.js
  backend/__tests__/unit/helpers/validators.js
  backend/__tests__/unit/models/user.js
  backend/__tests__/unit/models/verification.js
  backend/controllers/routes.js
  backend/controllers/user.js
  backend/controllers/vote.js
  backend/helpers/validators.js
  backend/middleware/auth.js
  backend/models/route.js
  backend/models/traffic.js
  backend/models/user.js
  backend/models/verification.js
  backend/package-lock.json
  backend/package.json
  backend/routes/routes.js
  backend/routes/user.js
  backend/server.js
  backend/services/email.js
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/actions/index.js
  frontend/src/actions/routes.js
  frontend/src/actions/userProfile.js
  frontend/src/components/createRoute.component.js
  frontend/src/components/createRouteDetails.component.js
  frontend/src/components/createRouteMap.component.js
  frontend/src/components/editProfile.component.js
  frontend/src/components/favouriteRoutes.component.js
  frontend/src/components/forgotPassword.component.js
  frontend/src/components/home.component.js
  frontend/src/components/login.component.js
  frontend/src/components/mapContainer.component.js
  frontend/src/components/markerComponent.component.js
  frontend/src/components/navbar.component.js
  frontend/src/components/overviewMap.component.js
  frontend/src/components/routePage.component.js
  frontend/src/components/signup.component.js
  frontend/src/components/useToken.js
  frontend/src/components/userCreatedRoutes.component.js
  frontend/src/components/userprofile.component.js
  frontend/src/index.js
  frontend/src/reducers/index.js
  frontend/src/reducers/routesReducer.js
  frontend/src/reducers/userProfileReducer.js
  frontend/src/reportWebVitals.js
Labels: High Priority, Pull Request

#138 Fix bug where verification code comparison is incorrect
  backend/controllers/user.js
Labels: Pull Request
