Repository tysonkaufmann/su-go, pull requests merged in 2021-02, with the labels that each got.

#54 Issue1
  .gitignore
  backend/.env
  backend/README.md
  backend/models/user.model.js
  backend/package-lock.json
  backend/package.json
  backend/routes/users.js
  backend/server.js
Labels: High Priority

#92 Login Backend Model and Endpoint
  .gitignore
  backend/.env
  backend/.jest.env.js
  backend/README.md
  backend/__tests__/integration/userAuth.js
  backend/__tests__/unit/controllers/userAuth.js
  backend/__tests__/unit/models/user.js
  backend/controllers/userAuth.js
  backend/package-lock.json
  backend/package.json
  backend/routes/routes.js
  backend/routes/user.js
  backend/server.js
  backend/validators/routes.js
  backend/validators/userAuth.js
Labels: Pull Request

#93 Issue-21 Backend for Password Reset
  backend/.gitignore
  backend/__tests__/integration/userAuth.js
  backend/__tests__/unit/controllers/userAuth.js
  backend/__tests__/unit/models/userAuth.js
  backend/__tests__/unit/models/verification.js
  backend/__tests__/unit/services/email.js
  backend/controllers/userAuth.js
  backend/models/userAuth.js
  backend/models/userInfo.js
  backend/models/verification.js
  backend/package-lock.json
  backend/package.json
  backend/routes/user.js
  backend/routes/userAuth.js
  backend/server.js
  backend/services/email.js
Labels: Pull Request

#96 Issue-34 Create a Get User Information Endpoint
  backend/__tests__/integration/userInformaiton.js
  backend/__tests__/unit/controllers/userInformation.js
  backend/controllers/userInformation.js
  backend/middleware/auth.js
  backend/routes/userInformation.js
  backend/server.js
Labels: Pull Request

#98 Setup GitHub Actions for automated testing
  .github/workflows/node.js.yml
  backend/.jest.env.js
  backend/__tests__/unit/services/email.js
  backend/package-lock.json
  backend/package.json
Labels: Pull Request

#100 Create endpoint for user profile update. Create Route model. Create endpoint for user created routes retrieval.
  backend/__tests__/integration/route.js
  backend/__tests__/integration/user.js
  backend/__tests__/unit/controllers/routes.js
  backend/__tests__/unit/controllers/user.js
  backend/__tests__/unit/models/user.js
  backend/controllers/routes.js
  backend/controllers/user.js
  backend/models/route.js
  backend/models/user.js
  backend/package.json
  backend/routes/routes.js
  backend/routes/user.js
Labels: Pull Request

#101 Add class and sequence diagrams
  README.md
  documentation/images/class diagram.png
  documentation/images/sequence - login.png
  documentation/images/sequence - logout.png
  documentation/images/sequence - resetpassword.png
  documentation/images/sequence - signup.png
  documentation/images/sequence - userprofile.png
  documentation/images/sequence - userroutes.png
Labels: Critical Priority, Pull Request, documentation
